serverAddr = "127.0.0.1"
serverPort = 7000

auth.method = "token"
auth.token = "my_secure_token_123"

[[proxies]]
name = "test-tcp"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6000
